#!/bin/bash

# Fix deprecated relative imports to absolute names. Relative imports doesn't
# work with python 3. Script finds all */osgeo/*.py files do replace with sed.

find . -type f -regex ".*/osgeo/.*\.py" -print | xargs sed -i \
    -e 's/^\(\s*\)from gdalconst import \*/\1from osgeo.gdalconst import \*/g' \
    -e 's/^\(\s*\)import gdalconst/\1from osgeo import gdalconst/g' \
    -e 's/^\(\s*\)import gdalnumeric/\1from osgeo import gdalnumeric/g' \
    -e 's/^\(\s*\)import gdal/\1from osgeo import gdal/g' \
    -e 's/^\(\s*\)from gdal_array import \*/\1from osgeo.gdal_array import \*/g' \
    -e 's/^\(\s*\)import osr/\1from osgeo import osr/g' \
    -e 's/^\(\s*\)import ogr/\1from osgeo import ogr/g' \
    -e 's/^\(\s*\)from \. import ogr/\1from osgeo import ogr/g' \
    -e 's/^\(\s*\)from \. import osr/\1from osgeo import osr/g' \
    -e 's/^\(\s*\)from \. import gdal/\1from osgeo import gdal/g'
